name: eslint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
