name: jest

on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install modules
        run: npm install

      - name: Run jest
        run: npm test
